### ISSUE TITLE
Get List of Emails Matching search query

### ISSUE THREAD

**Issue by mahsu** [bigredhacks/bigredhacks2016#141]
Output a comma separated list of emails matching a search query. This would help with finding bus captains.

**Comment by mahsu** [comment]
Upgrading back to blocker

**Comment by mahsu** [comment]
We could probably have this displayed as a collapsible comma separated list before the results table. Collapsed by default.

**Comment by GabrielEPerez** [comment]
Matt can you elaborate on your last comment pls?

**Comment by TrevorEdwards** [comment]
The current functionality allows you to get emails of everyone who is external, accepted, and on a bus route

**Comment by TrevorEdwards** [comment]
separated by bus route too

**Comment by mahsu** [comment]
I should specify that this issue now pertains to showing emails as part of the result of an arbitrary search query. On the search page

**Comment by GabrielEPerez** [comment]
Do we really need it or is our existing functionality okay?

**Comment by mahsu** [comment]
Existing functionality only has bus route data. This should reside on the search page and should work for any search query.
